#pragma once
#include <iostream>
#include <string>
#include <opencv2\opencv.hpp>
#include <filesystem>
#include "KronkoHelpers.h"
#include "CapImport.h"
#include "Cap.h"
#include "PackingLayouter.h"
#include "SquareLayouter.h"
#include "TriangleLayouter.h"
#include "ColorPicker.h"
#include "ColorPoint.h"
#include "ColorAvg.h"
#include "ColorCustom.h"
#include "ColorGauss.h"
#include "CapMap.h"
#include "CapAssembley.h"
#include "Types.h"
#include "KronkoConfig.h"
#include "KronkoGUI.h"