#pragma once
#include <iostream>
#include <string>
#include <opencv2\core\core.hpp>
#include <opencv2\highgui\highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <filesystem>
#include "CapImport.h"
#include "Cap.h"
#include "PackingLayouter.h"
#include "SquareLayouter.h"
#include "ColorPicker.h"
#include "ColorPoint.h"
#include "CapMap.h"